version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "start.sh", "backend"]
    volumes:
      - .:/app
    env_file:
      - backend.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "start.sh", "frontend"]
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: model_metrics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
