# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy entire project into container
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Default command (overridden by docker-compose)
CMD ["bash", "start.sh"]
# CMD ["python","-m", "Backend.main"]